services:
  web:
    build: .
    command: ./start-dev.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DORNASHOP_ENVIRONMENT=development
      - DORNASHOP_DEBUG=true
