"""record every support decision

Revision ID: 6b201e0cc081
Revises: b72f1a8c4d20
Create Date: 2026-09-06 16:50:09.707332

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b201e0cc081"
down_revision: str | None = "b72f1a8c4d20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "support_cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.Column("route", sa.String(length=32), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("intent", sa.String(length=32), nullable=True),
        sa.Column("reply", sa.Text(), nullable=True),
        sa.Column("citations", sa.JSON(), nullable=False),
        sa.Column("wording", sa.JSON(), nullable=False),
        sa.Column("reliability", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_support_cases_open", "support_cases", ["route", "closed_at"], unique=False
    )
    op.create_index(
        op.f("ix_support_cases_reference"), "support_cases", ["reference"], unique=True
    )
    op.create_index(
        op.f("ix_support_cases_user_id"), "support_cases", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_support_cases_user_id"), table_name="support_cases")
    op.drop_index(op.f("ix_support_cases_reference"), table_name="support_cases")
    op.drop_index("ix_support_cases_open", table_name="support_cases")
    op.drop_table("support_cases")
    # ### end Alembic commands ###
