fact = "proof_of_purchase"
locale = "en"
version = 1
approved = true

sentence = "Proof of purchase {proof_of_purchase_required} when you send something back."

[words]
proof_of_purchase_required_true = "is needed"
proof_of_purchase_required_false = "is not needed"
