fact = "proof_of_purchase"
locale = "fr"
version = 1
approved = true

sentence = "Une preuve d'achat {proof_of_purchase_required} pour tout retour."

[words]
proof_of_purchase_required_true = "est exigée"
proof_of_purchase_required_false = "n'est pas exigée"
